// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const cancelTask = `-- name: CancelTask :execrows
UPDATE tasks SET cancel_requested=1 WHERE id=? AND state IN ('queued','running') AND cancellable=1
`

func (q *Queries) CancelTask(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearLatest = `-- name: ClearLatest :exec
UPDATE settings SET latest_task=NULL WHERE singleton=1
`

func (q *Queries) ClearLatest(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearLatest)
	return err
}

const clearPending = `-- name: ClearPending :exec
DELETE FROM pending
`

func (q *Queries) ClearPending(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearPending)
	return err
}

const commitTask = `-- name: CommitTask :execrows
UPDATE tasks SET cancellable=0 WHERE id=? AND state IN ('queued','running') AND cancel_requested=0
`

func (q *Queries) CommitTask(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, commitTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const configuration = `-- name: Configuration :one
SELECT id,url,enabled,port,secret,dashboard FROM configurations WHERE id=?
`

type ConfigurationRow struct {
	ID        string `json:"id"`
	URL       string `json:"url"`
	Enabled   bool   `json:"enabled"`
	Port      int    `json:"port"`
	Secret    string `json:"secret"`
	Dashboard bool   `json:"dashboard"`
}

func (q *Queries) Configuration(ctx context.Context, id string) (ConfigurationRow, error) {
	row := q.db.QueryRowContext(ctx, configuration, id)
	var i ConfigurationRow
	err := row.Scan(
		&i.ID,
		&i.URL,
		&i.Enabled,
		&i.Port,
		&i.Secret,
		&i.Dashboard,
	)
	return i, err
}

const controller = `-- name: Controller :one
SELECT enabled,port,secret FROM controller WHERE singleton=1
`

type ControllerRow struct {
	Enabled bool   `json:"enabled"`
	Port    int    `json:"port"`
	Secret  string `json:"secret"`
}

func (q *Queries) Controller(ctx context.Context) (ControllerRow, error) {
	row := q.db.QueryRowContext(ctx, controller)
	var i ControllerRow
	err := row.Scan(&i.Enabled, &i.Port, &i.Secret)
	return i, err
}

const coreVersion = `-- name: CoreVersion :one
SELECT version FROM core_version WHERE singleton=1 AND identity=?
`

func (q *Queries) CoreVersion(ctx context.Context, identity string) (string, error) {
	row := q.db.QueryRowContext(ctx, coreVersion, identity)
	var version string
	err := row.Scan(&version)
	return version, err
}

const createController = `-- name: CreateController :exec
INSERT INTO controller(singleton,enabled,port,secret) VALUES(1,?,?,?)
`

type CreateControllerParams struct {
	Enabled bool   `json:"enabled"`
	Port    int    `json:"port"`
	Secret  string `json:"secret"`
}

func (q *Queries) CreateController(ctx context.Context, arg CreateControllerParams) error {
	_, err := q.db.ExecContext(ctx, createController, arg.Enabled, arg.Port, arg.Secret)
	return err
}

const createDeployment = `-- name: CreateDeployment :exec
INSERT INTO deployment(singleton,kind,unit,listen_address) VALUES(1,?,?,?)
`

type CreateDeploymentParams struct {
	Kind          string `json:"kind"`
	Unit          string `json:"unit"`
	ListenAddress string `json:"listenAddress"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, createDeployment, arg.Kind, arg.Unit, arg.ListenAddress)
	return err
}

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO identity(singleton,protocol,public_key,private_key) VALUES(1,?,?,?)
`

type CreateIdentityParams struct {
	Protocol   int    `json:"protocol"`
	PublicKey  []byte `json:"publicKey"`
	PrivateKey []byte `json:"privateKey"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createIdentity, arg.Protocol, arg.PublicKey, arg.PrivateKey)
	return err
}

const createSettings = `-- name: CreateSettings :exec
INSERT INTO settings(singleton) VALUES(1)
`

func (q *Queries) CreateSettings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createSettings)
	return err
}

const dashboard = `-- name: Dashboard :one
SELECT version FROM dashboards WHERE id=?
`

func (q *Queries) Dashboard(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, dashboard, id)
	var version string
	err := row.Scan(&version)
	return version, err
}

const deleteConfiguration = `-- name: DeleteConfiguration :exec
DELETE FROM configurations WHERE id=?
`

func (q *Queries) DeleteConfiguration(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteConfiguration, id)
	return err
}

const deployment = `-- name: Deployment :one
SELECT kind,unit,listen_address FROM deployment WHERE singleton=1
`

type DeploymentRow struct {
	Kind          string `json:"kind"`
	Unit          string `json:"unit"`
	ListenAddress string `json:"listenAddress"`
}

func (q *Queries) Deployment(ctx context.Context) (DeploymentRow, error) {
	row := q.db.QueryRowContext(ctx, deployment)
	var i DeploymentRow
	err := row.Scan(&i.Kind, &i.Unit, &i.ListenAddress)
	return i, err
}

const fingerprint = `-- name: Fingerprint :one
SELECT fingerprint FROM tasks WHERE id=?
`

func (q *Queries) Fingerprint(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, fingerprint, id)
	var fingerprint string
	err := row.Scan(&fingerprint)
	return fingerprint, err
}

const identity = `-- name: Identity :one
SELECT protocol,public_key,private_key FROM identity WHERE singleton=1
`

type IdentityRow struct {
	Protocol   int    `json:"protocol"`
	PublicKey  []byte `json:"publicKey"`
	PrivateKey []byte `json:"privateKey"`
}

func (q *Queries) Identity(ctx context.Context) (IdentityRow, error) {
	row := q.db.QueryRowContext(ctx, identity)
	var i IdentityRow
	err := row.Scan(&i.Protocol, &i.PublicKey, &i.PrivateKey)
	return i, err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO tasks(id,action,state,phase,updated,result,error,hash,fingerprint,request,cancellable,started) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertTaskParams struct {
	ID          string `json:"id"`
	Action      string `json:"action"`
	State       string `json:"state"`
	Phase       string `json:"phase"`
	Updated     string `json:"updated"`
	Result      string `json:"result"`
	Error       string `json:"error"`
	Hash        string `json:"hash"`
	Fingerprint string `json:"fingerprint"`
	Request     []byte `json:"request"`
	Cancellable bool   `json:"cancellable"`
	Started     string `json:"started"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertTask,
		arg.ID,
		arg.Action,
		arg.State,
		arg.Phase,
		arg.Updated,
		arg.Result,
		arg.Error,
		arg.Hash,
		arg.Fingerprint,
		arg.Request,
		arg.Cancellable,
		arg.Started,
	)
	return err
}

const installed = `-- name: Installed :one
SELECT installed FROM settings WHERE singleton=1
`

func (q *Queries) Installed(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, installed)
	var installed bool
	err := row.Scan(&installed)
	return installed, err
}

const interruptTasks = `-- name: InterruptTasks :exec
UPDATE tasks SET cancellable=0,state='interrupted',error=?,updated=?,request=NULL WHERE state IN ('queued','running')
`

type InterruptTasksParams struct {
	Error   string `json:"error"`
	Updated string `json:"updated"`
}

func (q *Queries) InterruptTasks(ctx context.Context, arg InterruptTasksParams) error {
	_, err := q.db.ExecContext(ctx, interruptTasks, arg.Error, arg.Updated)
	return err
}

const latestTask = `-- name: LatestTask :one
SELECT latest_task FROM settings WHERE singleton=1 AND latest_task IS NOT NULL
`

func (q *Queries) LatestTask(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, latestTask)
	var latest_task sql.NullString
	err := row.Scan(&latest_task)
	return latest_task, err
}

const oldConfigurations = `-- name: OldConfigurations :many
SELECT id FROM configurations WHERE id<>? ORDER BY seq DESC LIMIT -1 OFFSET 2
`

func (q *Queries) OldConfigurations(ctx context.Context, id string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, oldConfigurations, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pending = `-- name: Pending :one
SELECT previous,next,was_running FROM pending WHERE singleton=1
`

type PendingRow struct {
	Previous   string `json:"previous"`
	Next       string `json:"next"`
	WasRunning bool   `json:"wasRunning"`
}

func (q *Queries) Pending(ctx context.Context) (PendingRow, error) {
	row := q.db.QueryRowContext(ctx, pending)
	var i PendingRow
	err := row.Scan(&i.Previous, &i.Next, &i.WasRunning)
	return i, err
}

const request = `-- name: Request :one
SELECT request FROM tasks WHERE id=?
`

func (q *Queries) Request(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, request, id)
	var request []byte
	err := row.Scan(&request)
	return request, err
}

const saveConfiguration = `-- name: SaveConfiguration :exec
INSERT INTO configurations(id,url,enabled,port,secret,dashboard) VALUES(?,?,?,?,?,?)
`

type SaveConfigurationParams struct {
	ID        string `json:"id"`
	URL       string `json:"url"`
	Enabled   bool   `json:"enabled"`
	Port      int    `json:"port"`
	Secret    string `json:"secret"`
	Dashboard bool   `json:"dashboard"`
}

func (q *Queries) SaveConfiguration(ctx context.Context, arg SaveConfigurationParams) error {
	_, err := q.db.ExecContext(ctx, saveConfiguration,
		arg.ID,
		arg.URL,
		arg.Enabled,
		arg.Port,
		arg.Secret,
		arg.Dashboard,
	)
	return err
}

const saveController = `-- name: SaveController :exec
UPDATE controller SET enabled=?,port=?,secret=? WHERE singleton=1
`

type SaveControllerParams struct {
	Enabled bool   `json:"enabled"`
	Port    int    `json:"port"`
	Secret  string `json:"secret"`
}

func (q *Queries) SaveController(ctx context.Context, arg SaveControllerParams) error {
	_, err := q.db.ExecContext(ctx, saveController, arg.Enabled, arg.Port, arg.Secret)
	return err
}

const saveCoreVersion = `-- name: SaveCoreVersion :exec
INSERT INTO core_version(singleton,identity,version) VALUES(1,?,?) ON CONFLICT(singleton) DO UPDATE SET identity=excluded.identity,version=excluded.version
`

type SaveCoreVersionParams struct {
	Identity string `json:"identity"`
	Version  string `json:"version"`
}

func (q *Queries) SaveCoreVersion(ctx context.Context, arg SaveCoreVersionParams) error {
	_, err := q.db.ExecContext(ctx, saveCoreVersion, arg.Identity, arg.Version)
	return err
}

const saveDashboard = `-- name: SaveDashboard :exec
INSERT INTO dashboards(id,version) VALUES(?,?)
`

type SaveDashboardParams struct {
	ID      string `json:"id"`
	Version string `json:"version"`
}

func (q *Queries) SaveDashboard(ctx context.Context, arg SaveDashboardParams) error {
	_, err := q.db.ExecContext(ctx, saveDashboard, arg.ID, arg.Version)
	return err
}

const savePending = `-- name: SavePending :exec
INSERT INTO pending(singleton,previous,next,was_running) VALUES(1,?,?,?) ON CONFLICT(singleton) DO UPDATE SET previous=excluded.previous,next=excluded.next,was_running=excluded.was_running
`

type SavePendingParams struct {
	Previous   string `json:"previous"`
	Next       string `json:"next"`
	WasRunning bool   `json:"wasRunning"`
}

func (q *Queries) SavePending(ctx context.Context, arg SavePendingParams) error {
	_, err := q.db.ExecContext(ctx, savePending, arg.Previous, arg.Next, arg.WasRunning)
	return err
}

const saveSettings = `-- name: SaveSettings :exec
UPDATE settings SET interfaces=?,release_proxy=? WHERE singleton=1
`

type SaveSettingsParams struct {
	Interfaces   string `json:"interfaces"`
	ReleaseProxy string `json:"releaseProxy"`
}

func (q *Queries) SaveSettings(ctx context.Context, arg SaveSettingsParams) error {
	_, err := q.db.ExecContext(ctx, saveSettings, arg.Interfaces, arg.ReleaseProxy)
	return err
}

const saveUpdates = `-- name: SaveUpdates :exec
INSERT INTO update_checks(singleton,checked_at,self_current,self_latest,self_state,self_error,core_current,core_latest,core_state,core_error,dashboard_current,dashboard_latest,dashboard_state,dashboard_error) VALUES(1,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(singleton) DO UPDATE SET checked_at=excluded.checked_at,self_current=excluded.self_current,self_latest=excluded.self_latest,self_state=excluded.self_state,self_error=excluded.self_error,core_current=excluded.core_current,core_latest=excluded.core_latest,core_state=excluded.core_state,core_error=excluded.core_error,dashboard_current=excluded.dashboard_current,dashboard_latest=excluded.dashboard_latest,dashboard_state=excluded.dashboard_state,dashboard_error=excluded.dashboard_error
`

type SaveUpdatesParams struct {
	CheckedAt        string `json:"checkedAt"`
	SelfCurrent      string `json:"selfCurrent"`
	SelfLatest       string `json:"selfLatest"`
	SelfState        string `json:"selfState"`
	SelfError        string `json:"selfError"`
	CoreCurrent      string `json:"coreCurrent"`
	CoreLatest       string `json:"coreLatest"`
	CoreState        string `json:"coreState"`
	CoreError        string `json:"coreError"`
	DashboardCurrent string `json:"dashboardCurrent"`
	DashboardLatest  string `json:"dashboardLatest"`
	DashboardState   string `json:"dashboardState"`
	DashboardError   string `json:"dashboardError"`
}

func (q *Queries) SaveUpdates(ctx context.Context, arg SaveUpdatesParams) error {
	_, err := q.db.ExecContext(ctx, saveUpdates,
		arg.CheckedAt,
		arg.SelfCurrent,
		arg.SelfLatest,
		arg.SelfState,
		arg.SelfError,
		arg.CoreCurrent,
		arg.CoreLatest,
		arg.CoreState,
		arg.CoreError,
		arg.DashboardCurrent,
		arg.DashboardLatest,
		arg.DashboardState,
		arg.DashboardError,
	)
	return err
}

const setInstalled = `-- name: SetInstalled :exec
UPDATE settings SET installed=1 WHERE singleton=1
`

func (q *Queries) SetInstalled(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, setInstalled)
	return err
}

const setLatestTask = `-- name: SetLatestTask :exec
UPDATE settings SET latest_task=? WHERE singleton=1
`

func (q *Queries) SetLatestTask(ctx context.Context, latestTask sql.NullString) error {
	_, err := q.db.ExecContext(ctx, setLatestTask, latestTask)
	return err
}

const settings = `-- name: Settings :one
SELECT interfaces,release_proxy FROM settings WHERE singleton=1
`

type SettingsRow struct {
	Interfaces   string `json:"interfaces"`
	ReleaseProxy string `json:"releaseProxy"`
}

func (q *Queries) Settings(ctx context.Context) (SettingsRow, error) {
	row := q.db.QueryRowContext(ctx, settings)
	var i SettingsRow
	err := row.Scan(&i.Interfaces, &i.ReleaseProxy)
	return i, err
}

const task = `-- name: Task :one
SELECT id,action,state,phase,updated,result,error,hash,downloaded,total,speed,cancellable,cancel_requested,started FROM tasks WHERE id=?
`

type TaskRow struct {
	ID              string  `json:"id"`
	Action          string  `json:"action"`
	State           string  `json:"state"`
	Phase           string  `json:"phase"`
	Updated         string  `json:"updated"`
	Result          string  `json:"result"`
	Error           string  `json:"error"`
	Hash            string  `json:"hash"`
	Downloaded      int     `json:"downloaded"`
	Total           int     `json:"total"`
	Speed           float64 `json:"speed"`
	Cancellable     bool    `json:"cancellable"`
	CancelRequested bool    `json:"cancelRequested"`
	Started         string  `json:"started"`
}

func (q *Queries) Task(ctx context.Context, id string) (TaskRow, error) {
	row := q.db.QueryRowContext(ctx, task, id)
	var i TaskRow
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.State,
		&i.Phase,
		&i.Updated,
		&i.Result,
		&i.Error,
		&i.Hash,
		&i.Downloaded,
		&i.Total,
		&i.Speed,
		&i.Cancellable,
		&i.CancelRequested,
		&i.Started,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :execrows
UPDATE tasks SET downloaded=?1,total=?2,speed=?3,cancellable=CASE ?4 WHEN 'queued' THEN cancellable WHEN 'running' THEN cancellable ELSE 0 END,state=?4,phase=?5,updated=?6,result=?7,error=?8,request=CASE ?4 WHEN 'queued' THEN request WHEN 'running' THEN request END WHERE id=?9
`

type UpdateTaskParams struct {
	Downloaded int     `json:"downloaded"`
	Total      int     `json:"total"`
	Speed      float64 `json:"speed"`
	State      string  `json:"state"`
	Phase      string  `json:"phase"`
	Updated    string  `json:"updated"`
	Result     string  `json:"result"`
	Error      string  `json:"error"`
	ID         string  `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTask,
		arg.Downloaded,
		arg.Total,
		arg.Speed,
		arg.State,
		arg.Phase,
		arg.Updated,
		arg.Result,
		arg.Error,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updates = `-- name: Updates :one
SELECT checked_at,self_current,self_latest,self_state,self_error,core_current,core_latest,core_state,core_error,dashboard_current,dashboard_latest,dashboard_state,dashboard_error FROM update_checks WHERE singleton=1
`

type UpdatesRow struct {
	CheckedAt        string `json:"checkedAt"`
	SelfCurrent      string `json:"selfCurrent"`
	SelfLatest       string `json:"selfLatest"`
	SelfState        string `json:"selfState"`
	SelfError        string `json:"selfError"`
	CoreCurrent      string `json:"coreCurrent"`
	CoreLatest       string `json:"coreLatest"`
	CoreState        string `json:"coreState"`
	CoreError        string `json:"coreError"`
	DashboardCurrent string `json:"dashboardCurrent"`
	DashboardLatest  string `json:"dashboardLatest"`
	DashboardState   string `json:"dashboardState"`
	DashboardError   string `json:"dashboardError"`
}

func (q *Queries) Updates(ctx context.Context) (UpdatesRow, error) {
	row := q.db.QueryRowContext(ctx, updates)
	var i UpdatesRow
	err := row.Scan(
		&i.CheckedAt,
		&i.SelfCurrent,
		&i.SelfLatest,
		&i.SelfState,
		&i.SelfError,
		&i.CoreCurrent,
		&i.CoreLatest,
		&i.CoreState,
		&i.CoreError,
		&i.DashboardCurrent,
		&i.DashboardLatest,
		&i.DashboardState,
		&i.DashboardError,
	)
	return i, err
}
